### PR TITLE
Create infobox plugin

### LINKED ISSUE #7: new plugin: infobox
As discussed in the call with @schul-cloud last week, a plugin for an infobox is desired.

We thought about two possible design ideas that we would like to discuss. As we need the `Slate` Plugin for editing capabilities these two ideas came to our mind:
1) Wrap the `Slate` Plugin in our `infobox` plugin (i.e. `<infobox><Slate /></infobox>`)
1) Extend the `Slate`plugin with an extra button to toggle the `infobox` style

How do you feel about these suggestions?

@jprberlin @Knorrke

### PR DESCRIPTION
**Pull request by FWirtz**
Here you go @Knorrke, please let us know what you think. 😊 
Simple, green-bordered layout plugin.
 
image

Fixes #7

### CODE REVIEW

**Comment by FWirtz** [comment]
@jprberlin @Knorrke moved this to a custom branch so needed to open a new PR.
You should be able to add your changes @Knorrke. 😊 🌴

**Comment by FWirtz** [comment]
Concerning your question @Knorrke:

> Did you get along with the documentation, or are there things to improve?
> Your feedback would help us a lot!

## The build/test process
We tested our plugin during development as follows:
1) write changes
1) build plugin
1) update plugin in `example/` by re-installing
1) look at what changed
1) start at 1 again

This is **painful**. There hopefully is a better way, but we didn't invest time in figuring out how.
Can I test it without building every time to `lib`?
Documenting that a little better would be awesome.
(Or just tell us how to, we could append to the docs 😉)

## Lerna
**Till date** we didn't really understand how Lerna works. A short paragraph about its use would be awesome.
PS If there is one that we just missed ignore this point. Sorry.

## The ideal (?) solution
We think that a CLI tool for creating a plugin would be ideal. Just like `npm init` there could be something like `ory-plugin init` that asks you for the name of your desired plugin and then touches the respective files accordingly.
Most of our time was spent on trying to understand which files are needed for building and setting everything up so that it works without errors. Coding was like 2 minutes.

Something like a template folder that contains a blank plugin with comments denoting what to change where would work as well at first. Might be easier.

## Couple dependencies missing
The build initially always failed because there were a couple devDependencies missing that we needed to install.

Please let us know how you feel about our (CC @Blubl) suggestions/comments.
We'd **love to help** you out to improve the process of creating new plugins.

**Comment by Knorrke** [comment]
Thank you so much :-) 
I improved the readme from your suggestions and added a plugin "template". Hope the changes help you with the build process, should be quite nice actually when setup correctly, with watch mode and hot reloading, so you don't have to restart or reload anything^^

A tool like `ory-plugin init` would be great, I've never done something like this, so if you want to help me with that I'd really appreciate it. For now i think the template solution works too.

**Comment by FWirtz** [comment]
Oh thank you!
I'll try your template right now to create a Code Highlighting plugin according to your comments (here #12).
I'll have a look at the CLI afterwards. 😊

**Pull request merged**
